// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go

// Package mock_metrics is a generated GoMock package.
package mock_metrics

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// ErrorHTTPRequestsInc mocks base method.
func (m *MockMetrics) ErrorHTTPRequestsInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ErrorHTTPRequestsInc")
}

// ErrorHTTPRequestsInc indicates an expected call of ErrorHTTPRequestsInc.
func (mr *MockMetricsMockRecorder) ErrorHTTPRequestsInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorHTTPRequestsInc", reflect.TypeOf((*MockMetrics)(nil).ErrorHTTPRequestsInc))
}

// HTTPSuccessPingRequestsInc mocks base method.
func (m *MockMetrics) HTTPSuccessPingRequestsInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HTTPSuccessPingRequestsInc")
}

// HTTPSuccessPingRequestsInc indicates an expected call of HTTPSuccessPingRequestsInc.
func (mr *MockMetricsMockRecorder) HTTPSuccessPingRequestsInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPSuccessPingRequestsInc", reflect.TypeOf((*MockMetrics)(nil).HTTPSuccessPingRequestsInc))
}

// SuccessHTTPRequestsInc mocks base method.
func (m *MockMetrics) SuccessHTTPRequestsInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SuccessHTTPRequestsInc")
}

// SuccessHTTPRequestsInc indicates an expected call of SuccessHTTPRequestsInc.
func (mr *MockMetricsMockRecorder) SuccessHTTPRequestsInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuccessHTTPRequestsInc", reflect.TypeOf((*MockMetrics)(nil).SuccessHTTPRequestsInc))
}
